image:
  repository: grafana/grafana
  tag: 10.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

grafana:
  adminUser: admin
  adminPassword: CHANGE_ME
  prometheusUrl: http://socialbook-prometheus:9090
