replicaCount: 2

image:
  repository: alazar111/socialbook-frontend
  tag: latest
  pullPolicy: Always

rolloutId: "fd0501f5f7e2ce637b228bbcbfb73013991bc251"

service:
  type: ClusterIP
  port: 80
#d§efined in order to set environment variables in the frontend container



env:
  VITE_API_BASE: /api
  VITE_KEYCLOAK_URL: https://keycloak.ltu-m7011e-11.se
  VITE_KEYCLOAK_REALM: Userenter
  VITE_KEYCLOAK_CLIENT_ID: socialbook
  FRONTEND_IMAGE_TAG: latest
