replicaCount: 1

image:
  repository: alazar111/socialbook-frontend
  tag: frontend-7e636e04a7e72ff432e9b5d85a2a1c7d230fcdd3

env:
  VITE_API_BASE: /api
  VITE_KEYCLOAK_URL: https://keycloak.204-168-223-99.nip.io
  VITE_KEYCLOAK_REALM: Userenter
  VITE_KEYCLOAK_CLIENT_ID: socialbook
  REVIEWS_UPSTREAM: socialbook-reviews:5000
  USERS_UPSTREAM: socialbook-users:5000
  SOCIAL_UPSTREAM: socialbook-social:5000
  NOTIFICATIONS_UPSTREAM: socialbook-notifications:5000
  BOOKLISTS_UPSTREAM: socialbook-booklists:5000
  FRONTEND_IMAGE_TAG: "frontend-7e636e04a7e72ff432e9b5d85a2a1c7d230fcdd3"
rolloutId: "7e636e04a7e72ff432e9b5d85a2a1c7d230fcdd3"
