postgres:
  storageClassName: local-path
  timezone: Europe/Stockholm
  user: keycloak
  password: CHANGE_ME_DB_PASSWORD
  image: postgres:16
  resourceLimit: false
  cpu: 1000m
  memory: 1000Mi
  storage: 5Gi

keycloak:
  replicas: 1
  image: quay.io/keycloak/keycloak:23.0
  adminUser: admin
  adminPassword: CHANGE_ME_ADMIN_PASSWORD
  database:
    vendor: postgres
    host: postgres-service
    port: 5432
    database: keycloak
    username: keycloak
    password: CHANGE_ME_DB_PASSWORD
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

domain: keycloak.204-168-223-99.nip.io
email: your-email@example.com
certIssuer: letsencrypt-prod

service:
  port: 80
  targetPort: 8080

ingress:
  className: traefik
  tlsSecretName: keycloak-tls
