image:
  repository: alazar111/socialbook-notifications-worker
  tag: worker-9cc4f1a414171a5750bdf0504b258b75600f6090

env:
  RABBITMQ_URL: amqp://socialbook:CHANGE_ME@rabbitmq-service-api:5672
  RABBITMQ_EXCHANGE: socialbook.events
  RABBITMQ_QUEUE: socialbook.notifications
  RABBITMQ_ROUTING_KEYS: review.commented,booklist.updated
  NOTIFICATIONS_API_URL: http://socialbook-notifications:5000/internal/notifications
