image:
  repository: yourdockerhub/socialbook-backend
  tag: latest

env:
  MONGODB_URI: mongodb://socialbook-mongo-notifications:27017/notifications
  KEYCLOAK_URL: https://keycloak.204-168-223-99.nip.io
  KEYCLOAK_REALM: Userenter
  CORS_ALLOWED_ORIGINS: https://socialbook.204-168-223-99.nip.io
