image:
  repository: alazar111/socialbook-backend
  tag: backend-96b02e07fd640c7d9548c144342aeb8c456807c9

env:
  MONGODB_URI: mongodb://socialbook-mongo-notifications:27017/notifications
  KEYCLOAK_URL: https://keycloak.204-168-223-99.nip.io
  KEYCLOAK_REALM: Userenter
  CORS_ALLOWED_ORIGINS: https://socialbook.204-168-223-99.nip.io
