image:
  repository: alazar111/socialbook-notifications-worker
  tag: worker-248d7494c56ffafcd0523c40f22e559e70181b9f

env:
  RABBITMQ_URL: amqp://socialbook:CHANGE_ME@rabbitmq-service-api:5672
  RABBITMQ_EXCHANGE: socialbook.events
  RABBITMQ_QUEUE: socialbook.notifications
  RABBITMQ_ROUTING_KEYS: review.commented,booklist.updated
  NOTIFICATIONS_API_URL: http://socialbook-notifications:5000/internal/notifications
