image:
  repository: alazar111/socialbook-notifications-worker
  tag: worker-69547c54eaba8c731fe99ad5e9e9d0b42ad44d12

env:
  RABBITMQ_URL: amqp://socialbook:CHANGE_ME@rabbitmq-service-api:5672
  RABBITMQ_EXCHANGE: socialbook.events
  RABBITMQ_QUEUE: socialbook.notifications
  RABBITMQ_ROUTING_KEYS: review.commented,booklist.updated
  NOTIFICATIONS_API_URL: http://socialbook-notifications:5000/internal/notifications
