image:
  repository: alazar111/socialbook-backend
  tag: backend-8c6f21b2e3a4bb4fc21aa5832201f3700d37bda8

env:
  MONGODB_URI: mongodb://socialbook-mongo-notifications:27017/notifications
  KEYCLOAK_URL: https://keycloak.204-168-223-99.nip.io
  KEYCLOAK_REALM: Userenter
  CORS_ALLOWED_ORIGINS: https://socialbook.204-168-223-99.nip.io
