image:
  repository: alazar111/socialbook-backend
  tag: backend-d742273cfd9f0341cf26d299f8951838379f64cb

env:
  MONGODB_URI: mongodb://socialbook-mongo-reviews:27017/reviews
  KEYCLOAK_URL: https://keycloak.204-168-223-99.nip.io
  KEYCLOAK_REALM: Userenter
  RABBITMQ_URL: amqp://socialbook:CHANGE_ME@rabbitmq-service-api.rabbitmq.svc.cluster.local:5672
  CORS_ALLOWED_ORIGINS: https://socialbook.204-168-223-99.nip.io
  BACKEND_IMAGE_TAG: latest
