image:
  repository: alazar111/socialbook-backend
  tag: backend-b323c8caca957724bffd1f83c9580c9878dabf71

env:
  MONGODB_URI: mongodb://socialbook-mongo-reviews:27017/reviews
  KEYCLOAK_URL: https://keycloak.204-168-223-99.nip.io
  KEYCLOAK_REALM: Userenter
  RABBITMQ_URL: amqp://socialbook:CHANGE_ME@rabbitmq-service-api:5672
  CORS_ALLOWED_ORIGINS: https://socialbook.204-168-223-99.nip.io
  BACKEND_IMAGE_TAG: latest
