image:
  repository: alazar111/socialbook-backend
  tag: backend-c00f8db645f7bd8d5364def36989d4d3bcb2fa60

env:
  MONGODB_URI: mongodb://socialbook-mongo-social:27017/social
  KEYCLOAK_URL: https://keycloak.204-168-223-99.nip.io
  KEYCLOAK_REALM: Userenter
  BOOKLISTS_SERVICE_URL: http://socialbook-booklists:5000
  CORS_ALLOWED_ORIGINS: https://socialbook.204-168-223-99.nip.io
