image:
  repository: alazar111/socialbook-notifications
  tag: dd3aa1b52630e3798edf7ba14a46dfa2072b28d5

replicaCount: 1

env:
  MONGODB_URI: mongodb://mongo-vm.example.internal:27017/notifications
  KEYCLOAK_URL: https://keycloak.example.com
  KEYCLOAK_REALM: Userenter
