image:
  repository: alazar111/socialbook-notifications
  tag: latest

replicaCount: 1

env:
  MONGODB_URI: mongodb://mongo-vm.example.internal:27017/notifications
  KEYCLOAK_URL: https://keycloak.example.com
  KEYCLOAK_REALM: Userenter
