image:
  repository: alazar111/socialbook-notifications
  tag: 39be0674417fd35979d24ef024d4a944d3ffdba4

replicaCount: 1

env:
  MONGODB_URI: mongodb://mongo-vm.example.internal:27017/notifications
  KEYCLOAK_URL: https://keycloak.example.com
  KEYCLOAK_REALM: Userenter
