replicaCount: 1

command:
  - node
  - dist/apps/social/main.js

env:
  MONGODB_URI: mongodb://mongo-vm.example.internal:27017/social
  KEYCLOAK_URL: https://keycloak.example.com
  KEYCLOAK_REALM: Userenter
  BOOKLISTS_SERVICE_URL: http://socialbook-booklists:5000
