image:
  repository: alazar111/socialbook-users
  tag: latest

replicaCount: 1

env:
  MONGODB_URI: mongodb://mongo-vm.example.internal:27017/users
  KEYCLOAK_URL: https://keycloak.example.com
  KEYCLOAK_REALM: Userenter
  KEYCLOAK_ADMIN_CLIENT_ID: socialbook-admin
  KEYCLOAK_ADMIN_CLIENT_SECRET: CHANGE_ME
  KEYCLOAK_PUBLIC_CLIENT_ID: socialbook
