# RabbitMQ Configuration
Image: "rabbitmq:3-management"

# RabbitMQ Credentials
# ⚠️ IMPORTANT: Change these for production!
RabbitMQUser: "alazar111"
RabbitMQPassword: "HelloWorld123"

# Persistent storage
PersistenceEnabled: true
PersistenceSize: "8Gi"
