replicaCount: 1

image:
  repository: alazar111/socialbook-backend
  tag: latest
  pullPolicy: Always

command:
  - node
  - dist/apps/notifications/main.js

service:
  type: ClusterIP
  port: 5000

env:
  MONGODB_URI: mongodb://socialbook-mongo-notifications:27017/notifications
  KEYCLOAK_URL: https://keycloak.ltu-m7011e-11.se
  KEYCLOAK_REALM: Userenter
