apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../monitoring/10-prometheus-rbac.yaml
  - ../monitoring/11-prometheus-config.yaml
  - ../monitoring/12-prometheus.yaml
  - ../monitoring/13-prometheus-alerts.yaml
  - ../monitoring/15-blackbox-exporter.yaml
  - ../monitoring/20-node-exporter.yaml
  - ../monitoring/30-kube-state-metrics.yaml
