apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 10-prometheus-rbac.yaml
  - 11-prometheus-config.yaml
  - 12-prometheus.yaml
  - 13-prometheus-alerts.yaml
  - 15-blackbox-exporter.yaml
  - 20-node-exporter.yaml
  - 30-kube-state-metrics.yaml
